services:
  - docker

jobs:
  include:
    - stage: build
      script: make build

    - stage: deploy
      script: ""
      deploy:
        provider: script
        script: make push
        on:
          branch: master

notifications:
  pushover:
    on_success: change
    on_failure: always
    api_key:
      secure: 
    users:
      secure: 
